version: "2.4"

services:
  backend:
    build: backend
    ports:
      - "5000:5000"
    mem_limit: 6000m

  frontend:
    build: frontend
    volumes:
      - node-modules:/frontend/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - backend
    mem_limit: 1000m

volumes:
    node-modules:
