version: "3.7"

services:
  backend:
    build: backend
    ports:
      - "5000:5000"

  frontend:
    build: frontend
    volumes:
      - node-modules:/frontend/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
    node-modules:
