version: "2.4"

services:
  small_backend:
    image: nichollskc/thecanonsmouth_backend_small
    build: backend
    ports:
      - "1000:1000"
    mem_limit: 4000m

  small_frontend:
    image: nichollskc/thecanonsmouth_frontend_small
    build: frontend
    volumes:
      - node-modules:/frontend/node_modules
    ports:
      - '2000:2000'
    depends_on:
      - small_backend
    mem_limit: 300m

volumes:
    node-modules:
